# Step 1: Build the React app
FROM node:18-alpine AS builder

LABEL author="dusehd1 <angrybird2600@gmail.com>, dmstjd, alswl"
LABEL description="24-1 객체지향분석및설계 팀프로젝트 - 백엔드"

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Step 2: Serve the React app with Nginx
FROM nginx:alpine

COPY --from=builder /usr/src/app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
